### ISSUE TITLE
Configuración del Proyecto

### ISSUE THREAD

**Issue by treeskelt** [treeskelt/neutron#1]

**Comment by treeskelt** [comment]
@cesarp Solo para empezar oficialmente el proyecto

**Comment by treeskelt** [comment]
@cesarp Propongo la siguiente lista de librerias, basado en la conversación que tuvimos:

- Task runner: [Gulp](http://gulpjs.com/)
- Module Bundler: [Webpack](http://webpack.github.io/)
- Transpiler: [Babel](https://babeljs.io/)
- Components: [React](https://facebook.github.io/react/)
- Flux: [Flummox](https://github.com/acdlite/flummox)
- Router: [React router](https://github.com/rackt/react-router)
- Stores: [Immutable](http://facebook.github.io/immutable-js/) with [ImmutableRenderMixin](https://www.npmjs.com/package/react-immutable-render-mixin)
- Unit Testing: [Jest](https://facebook.github.io/jest/)

¿Alguna otra propuesta?

**Comment by cesarp** [comment]
https://github.com/callemall/material-ui

**Comment by treeskelt** [comment]
¿En lugar de [Materialize](http://materializecss.com) o agregándolo?

**Comment by cesarp** [comment]
En lugar de.

**Comment by treeskelt** [comment]
Listo. Lo cierro y lo pongo en la wiki.
